### ISSUE TITLE
Missing catch for failed DNS on calling Deepstack

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#271]
```
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to call DeepStack at http://deepstack-ai:5000/: Error: getaddrinfo ENOTFOUND deepstack-ai
    at /home/node/app/bundle.js:721:24164
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

_Originally posted by @Viksie in https://github.com/danecreekphotography/node-deepstackai-trigger/issues/260#issuecomment-646362421_

**Comment by Viksie** [comment]
Man, you're fast !
